version: '3.4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./packages/public/server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  #  editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/editor-renderer/Dockerfile
  editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-editor-renderer

  #  legacy-editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/legacy-editor-renderer/Dockerfile
  legacy-editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-legacy-editor-renderer

  server-composer:
    image: composer:1.8
    volumes:
      - ./packages/public/server/composer.json:/app/composer.json:cached
      - ./packages/public/server/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/src/module:/app/src/module:cached
      - ./packages/public/server/src/vendor:/app/src/vendor:cached

  server-httpd:
    build:
      context: packages/public/server
      dockerfile: docker/httpd/Dockerfile
      target: base
    ports:
      - '4567:80'
    volumes:
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
    environment:
      - PHP_HOST=server-php

  server-php:
    build:
      context: packages/public/server
      dockerfile: docker/php/Dockerfile
      target: base
    volumes:
      - ./packages/public/server/dev-tools/vendor:/usr/local/apache2/htdocs/dev-tools/vendor:delegated
      - ./packages/public/server/package.json:/usr/local/apache2/htdocs/package.json:delegated
      - ./packages/public/server/phpunit.xml:/usr/local/apache2/htdocs/phpunit.xml:delegated
      - ./packages/public/server/src/config:/usr/local/apache2/htdocs/src/config:delegated
      - ./packages/public/server/src/lang:/usr/local/apache2/htdocs/src/lang:delegated
      - ./packages/public/server/src/module:/usr/local/apache2/htdocs/src/module:delegated
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
      - ./packages/public/server/src/test:/usr/local/apache2/htdocs/src/test:delegated
      - ./packages/public/server/src/vendor:/usr/local/apache2/htdocs/src/vendor:delegated
      - ./packages/public/server/src/init_autoloader.php:/usr/local/apache2/htdocs/src/init_autoloader.php:delegated

  server-migrate:
    build:
      context: packages/migrations
    volumes:
      - ./packages/migrations/dist:/usr/src/app/migrations:delegated
    environment:
      - DATABASE=mysql://root:secret@mysql:3306/serlo?query

  static-assets:
    image: nginx
    ports:
      - '8082:80'
    volumes:
      - ./packages/public/static-assets/src:/usr/share/nginx/html:delegated

networks:
  default:
    # Override the network name so that we can rely on that in serlo.org-hydra
    name: "serlo.org-network"
